@extends('app')

@section('title', 'Password Generator')

@section('content')

    <div class="container" id="app">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1 text-center">
                <h1 class="title">Colemak Password Generator</h1>
            </div>
        </div>

        @include('keyboard')

        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1 text-center">
                <div class="password-display">@{{ password }}</div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1 text-center">
                <h2 class="question">Password Options</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-4 col-xs-10 col-xs-offset-1">
                <div>
                    <input type="checkbox" v-model="shift" id="shiftCheckbox" v-on:change="update"> Use shift key
                </div>
                <div>
                    <input type="checkbox" v-model="reach" id="reachCheckbox" v-on:change="update"> Include "hard to reach" keys
                </div>
                <div>
                    <select class="number-input form-inline" v-model="letterSelect" v-on:change="update">
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                        <option selected>6</option>
                        <option>7</option>
                        <option>8</option>
                        <option>9</option>
                        <option>10</option>
                        <option>11</option>
                        <option>12</option>
                    </select> "Common" letters <span class="key-group">@{{ letters }}</span>
                </div>
                <div>
                    <select class="number-input form-inline" v-model="numberSelect" v-on:change="update">
                        <option>0</option>
                        <option>1</option>
                        <option selected>2</optionchecked>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select> Numbers <span class="key-group">@{{ numbers }}</span>
                </div>
                <div>
                    <select class="number-input form-inline" v-model="punctuationSelect" v-on:change="update">
                        <option>0</option>
                        <option selected>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select> Punctuation symbols <span class="key-group">@{{ punctuation }}</span>
                </div>
                <div>
                    <select class="number-input form-inline" v-model="specialSelect" v-on:change="update">
                        <option>0</option>
                        <option selected>1</option>
                        <option>2</option>
                        <option>3</option>
                        <option>4</option>
                        <option>5</option>
                    </select> Special characters <span class="key-group">@{{ special }}@{{ reachKeys }}</span>
                </div>
            </div>
        </div>
        <hr class="divider col-md-2 col-md-offset-5">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1 text-center">
                <h2 class="question">What is this?</h2>
                <p class="text-justify">This page will generate random passwords using the common keys on a Qwerty and Colemak layouts. When using a software implementation of Colemak, system passwords might need to be typed on a Qwerty keyboard. Using a password from this page will allow a Colemak typist to continue to touch type without worry of which layout is active.</p>
                <h2 class="question">What the heck is Colemak?</h2>
                <p class="text-justify"><a href="https://colemak.com/">Colemak</a> is an alternate (to Qwerty) keyboard layout similar in conception to the Dvorak layout. Keys are rearranged based on frequency and ergonomic concerns. Colemak differs from Dvorak in that it has ten keys in common with the Qwerty layout.</p>
                <h2 class="question">Wait, is that a good idea?</h2>
                <p class="text-justify">Of course not. The possible number of letters in a password generated by this page is only a third that of a password using all the letters in the alphabet. That means even a long password becomes immensly easier to break if it is known that your password uses an abbreviated alphabet. It's <script>document.write(new Date().getFullYear())</script> you should be using a password manager already. You shouldn't be memorizing passwords anymore. So seriously, don't use this. </p>
            </div>
        </div>

    </div>

@endsection